name: Artifact between jobs 

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest

    steps:
      - name: Create File 
        run: |
          echo "Hello from job 1"> file.txt
          echo "Time: $(date)" >> file.txt
      - name: Upload Artifact
        uses: actions/upload-artifact@v5
        with:
          name: shared-file
          path: file.txt   
  job2:
    runs-on: ubuntu-latest
    needs: job1

    steps:
      - name : Download artifact
        uses: actions/download-artifact@v5
        with:
          name: shared-file
      - name: Read File 
        run: cat file.txt    

      