name: Multi-os system 

on: push

jobs:
  ubuntu-jobs:
    runs-on: ubuntu-runner
    steps:
      - name: Print details
        run: |
          echo "OS: ubuntu"
          hostname
          whoami

  windows-jobs:
    runs-on: windows-latest
    steps:
      - name: Print Details
        run: |
          echo OS : Windows 
          hostname
          whoami

  macos-job:
    runs-on: macos-latest
    steps:
      - name: Print details
        run: |
          echo "OS : macos"
          hostname
          whoami

  check-tools:
    runs-on: ubuntu-latest
    steps:
      - name: Check version
        run: |
          docker --version
          python --version
          node --version
          git --version



