name: Secrets Demo

on : [push]

jobs:
  check-secret:
    runs-on: ubuntu-latest

    steps:
      - name: Check if secret exists
        run : |
          if [ -n "${{ secrets.MY_SECRET_MESSAGE }}" ]; then
            echo "The seccret is set True"
          else
            echo "The secret is Not set"
          fi

      - name: Try printing secret (Masked)
        run: echo "Secret Value : ${{ secrets.MY_SECRET_MESSAGE }}"