name: Use Secrets Safely 

on: [push]

jobs:
  use-secreate:
    runs-on: ubuntu-latest
     
    steps:
      - name: Use Secret as env 
        env:
          SECRET_MSG: ${{ secrets.MY_SECRET_MESSAGE }}
        run: |
          echo "secret is being used safely"
          echo "Length of secret : ${#SECRET_MSG}"
      - name: Simulate Docker login (no real login)
        env:
          USERNAME: ${{ secrets.DOCKER_USERNAME }}        
          TOKEN: ${{ secrets.DOCKER_TOKEN }}
        run: |
          echo "Logging into docker simulated "
          echo "Username is set : ${#USERNAME} characters"
          echo "Token is set: ${#TOKEN} Characters"
            
          